services:
  drupal:
    image: ghcr.io/seek-key-ltd/drupal/drupal-redis:latest
    container_name: drupal
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - REDIS_HOST=dragonfly
      - REDIS_PORT=6379
      - DB_TYPE=mysql
      - DB_HOST=proxysql
      - DB_PORT=6033
      - DB_USER=admin
      - DB_PASS=CZTqVMU9oMercE#
      - DB_NAME=drupal
    labels:
      - traefik.enable=true
      - traefik.http.routers.drupal.rule=Host("drupal.seekkey.eu.org")
      - traefik.http.routers.drupal.entrypoints=websecure
      - traefik.http.routers.drupal.tls.certresolver=cloudflare
    volumes:
      - /opt/drupal/modules:/opt/drupal/modules:ro
      - /opt/drupal/profiles:/opt/drupal/profiles:ro
      - /opt/drupal/sites:/opt/drupal/web/sites
      - /opt/drupal/themes:/opt/drupal/themes:ro

networks:
  traefik:
    external: true
